apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP   # Internal service within the cluster
  selector:
    app: backend
  ports:
    - port: 8000         # Port exposed by the service inside the cluster
      targetPort: 80     # Port on the container the service forwards to
